#ifndef SDKCONFIG_H
#define SDKCONFIG_H

#define SDKCONFIG_BOARD "RISCV"
#define SDKCONFIG_CHIP "CH32V307VCT6"
#define SDKCONFIG_CHIP_SERIES "CH32"
#define SDKCONFIG_CHIP_SUBSERIES "CH32V3"
#define SDKCONFIG_CHIP_VENDOR "WCH"
#define SDKCONFIG_LAST_MODIFIED "2025-11-30 23:57:55"

// 管脚定义说明:
// USART0 - TX: PA9
// USART0 - RX: PA10
// USART0 - speed: 9600
// USART2 - TX: PA11
// USART2 - RX: PA12
// USART3 - TX: PA13
// USART3 - RX: PA14
// SPI1 - SCK: PB12
// SPI1 - MISO: PB13
// SPI1 - MOSI: PB14
// SPI1 - CS: PB15
// SPI2 - SCK: PB12
// SPI2 - MISO: PC13
// SPI2 - MOSI: PC14
// SPI2 - CS: PC15
// SPI3 - SCK: PD12
// SPI3 - MISO: PD13
// SPI3 - MOSI: PD14
// SPI3 - CS: PC15
// I2C1 - SCL: PB6
// I2C1 - SDA: PB7
// I2C2 - SCL: PB8
// I2C2 - SDA: PB9
// I2C3 - SCL: PA8
// I2C3 - SDA: PC9
// ADC1 - IN0: PA0
// ADC2 - IN0: PA1
// GPIOD - KEY0: PD0
// GPIOD - KEY1: PD1
// GPIOD - KEY2: PD3
// GPIOD - KEY3: PD4
// GPIOD - LED5: PD8
// GPIOD - LED6: PD10

#define SDK_USING_USART0
#define SDK_USING_USART0_TX "PA9"
#define SDK_USING_USART0_RX "PA10"
#define SDK_USING_USART0_SPEED "9600"
#define SDK_USING_USART2
#define SDK_USING_USART2_TX "PA11"
#define SDK_USING_USART2_RX "PA12"
#define SDK_USING_USART3
#define SDK_USING_USART3_TX "PA13"
#define SDK_USING_USART3_RX "PA14"
#define SDK_USING_SPI1
#define SDK_USING_SPI1_SCK "PB12"
#define SDK_USING_SPI1_MISO "PB13"
#define SDK_USING_SPI1_MOSI "PB14"
#define SDK_USING_SPI1_CS "PB15"
#define SDK_USING_SPI2
#define SDK_USING_SPI2_SCK "PB12"
#define SDK_USING_SPI2_MISO "PC13"
#define SDK_USING_SPI2_MOSI "PC14"
#define SDK_USING_SPI2_CS "PC15"
#define SDK_USING_SPI3
#define SDK_USING_SPI3_SCK "PD12"
#define SDK_USING_SPI3_MISO "PD13"
#define SDK_USING_SPI3_MOSI "PD14"
#define SDK_USING_SPI3_CS "PC15"
#define SDK_USING_I2C1
#define SDK_USING_I2C1_SCL "PB6"
#define SDK_USING_I2C1_SDA "PB7"
#define SDK_USING_I2C2
#define SDK_USING_I2C2_SCL "PB8"
#define SDK_USING_I2C2_SDA "PB9"
#define SDK_USING_I2C3
#define SDK_USING_I2C3_SCL "PA8"
#define SDK_USING_I2C3_SDA "PC9"
#define SDK_USING_ADC1
#define SDK_USING_ADC1_IN0 "PA0"
#define SDK_USING_ADC2
#define SDK_USING_ADC2_IN0 "PA1"
#define SDK_USING_GPIOA
#define SDK_USING_GPIOB
#define SDK_USING_GPIOC
#define SDK_USING_GPIOD
#define SDK_USING_GPIOD_KEY0 "PD0"
#define SDK_USING_GPIOD_KEY1 "PD1"
#define SDK_USING_GPIOD_KEY2 "PD3"
#define SDK_USING_GPIOD_KEY3 "PD4"
#define SDK_USING_GPIOD_LED5 "PD8"
#define SDK_USING_GPIOD_LED6 "PD10"
#define SDK_USING_GPIOE
#define SDK_USING_GPIOF
#define SDK_USING_GPIOG
#define SDK_USING_USR1
#define SDK_USING_USR2
#define SDK_USING_USR3
#define SDK_USING_SFUD
#define SDK_USING_SHELL
#define SDK_USING_USR
#define SDK_USING_TESTCASE_UART
#define SDK_USING_TESTCASE_LED
#define SDK_USING_TESTCASE_GUI
#define SDK_USING_TESTCASE_SHELL

#endif /* SDKCONFIG_H */