#ifndef SDKCONFIG_H
#define SDKCONFIG_H

#define SDKCONFIG_BOARD "RISCV"
#define SDKCONFIG_CHIP "CH32V307VCT6"
#define SDKCONFIG_CHIP_SERIES "CH32"
#define SDKCONFIG_CHIP_SUBSERIES "CH32V3"
#define SDKCONFIG_CHIP_VENDOR "WCH"
#define SDKCONFIG_LAST_MODIFIED "2025-12-09 22:19:12"

// 管脚定义说明:
// USART2 - TX: PD5
// USART2 - RX: PD6
// USART2 - BaudRate: 9600
// USART2 - ISR: 1
// UART4 - TX: PB0
// UART4 - RX: PB1
// UART4 - BaudRate: 9600
// UART4 - ISR: 0
// UART6 - TX: PC0
// UART6 - RX: PC1
// UART6 - BaudRate: 9600
// UART6 - ISR: 0
// UART7 - TX: PE12
// UART7 - RX: PE13
// UART7 - BaudRate: 115200
// UART7 - ISR: 0
// UART8 - TX: PE14
// UART8 - RX: PE15
// UART8 - BaudRate: 115200
// UART8 - ISR: 0
// SPI1 - SCK: PB12
// SPI1 - MISO: PB13
// SPI1 - MOSI: PB14
// SPI1 - CS: PB15
// SPI2 - SCK: PB12
// SPI2 - MISO: PC13
// SPI2 - MOSI: PC14
// SPI2 - CS: PC15
// SPI3 - SCK: PD12
// SPI3 - MISO: PD13
// SPI3 - MOSI: PD14
// SPI3 - CS: PC15
// I2C1 - SCL: PB6
// I2C1 - SDA: PB7
// I2C2 - SCL: PB8
// I2C2 - SDA: PB9
// I2C3 - SCL: PA8
// I2C3 - SDA: PC9
// ADC1 - IN0: PA0
// ADC2 - IN0: PA1
// GPIOD - KEY0: PD0
// GPIOD - KEY1: PD1
// GPIOD - KEY2: PD3
// GPIOD - KEY3: PD4
// GPIOD - LED5: PD8
// GPIOD - LED6: PD10

#define SDK_USING_USART2
#define SDK_USING_USART2_DEVICE USART2
#define SDK_USING_USART2_TX "PD5"
#define SDK_USING_USART2_RX "PD6"
#define SDK_USING_USART2_BAUDRATE 9600
#define SDK_USING_USART2_ISR 1
#define SDK_USING_UART4
#define SDK_USING_UART4_DEVICE UART4
#define SDK_USING_UART4_TX "PB0"
#define SDK_USING_UART4_RX "PB1"
#define SDK_USING_UART4_BAUDRATE 9600
#define SDK_USING_UART4_ISR 0
#define SDK_USING_UART6
#define SDK_USING_UART6_DEVICE UART6
#define SDK_USING_UART6_TX "PC0"
#define SDK_USING_UART6_RX "PC1"
#define SDK_USING_UART6_BAUDRATE 9600
#define SDK_USING_UART6_ISR 0
#define SDK_USING_UART7
#define SDK_USING_UART7_DEVICE UART7
#define SDK_USING_UART7_TX "PE12"
#define SDK_USING_UART7_RX "PE13"
#define SDK_USING_UART7_BAUDRATE 115200
#define SDK_USING_UART7_ISR 0
#define SDK_USING_UART8
#define SDK_USING_UART8_DEVICE UART8
#define SDK_USING_UART8_TX "PE14"
#define SDK_USING_UART8_RX "PE15"
#define SDK_USING_UART8_BAUDRATE 115200
#define SDK_USING_UART8_ISR 0
#define SDK_USING_SPI1
#define SDK_USING_SPI1_DEVICE SPI1
#define SDK_USING_SPI1_SCK "PB12"
#define SDK_USING_SPI1_MISO "PB13"
#define SDK_USING_SPI1_MOSI "PB14"
#define SDK_USING_SPI1_CS "PB15"
#define SDK_USING_SPI2
#define SDK_USING_SPI2_DEVICE SPI2
#define SDK_USING_SPI2_SCK "PB12"
#define SDK_USING_SPI2_MISO "PC13"
#define SDK_USING_SPI2_MOSI "PC14"
#define SDK_USING_SPI2_CS "PC15"
#define SDK_USING_SPI3
#define SDK_USING_SPI3_DEVICE SPI3
#define SDK_USING_SPI3_SCK "PD12"
#define SDK_USING_SPI3_MISO "PD13"
#define SDK_USING_SPI3_MOSI "PD14"
#define SDK_USING_SPI3_CS "PC15"
#define SDK_USING_I2C1
#define SDK_USING_I2C1_DEVICE I2C1
#define SDK_USING_I2C1_SCL "PB6"
#define SDK_USING_I2C1_SDA "PB7"
#define SDK_USING_I2C2
#define SDK_USING_I2C2_DEVICE I2C2
#define SDK_USING_I2C2_SCL "PB8"
#define SDK_USING_I2C2_SDA "PB9"
#define SDK_USING_I2C3
#define SDK_USING_I2C3_DEVICE I2C3
#define SDK_USING_I2C3_SCL "PA8"
#define SDK_USING_I2C3_SDA "PC9"
#define SDK_USING_ADC1
#define SDK_USING_ADC1_DEVICE ADC1
#define SDK_USING_ADC1_IN0 "PA0"
#define SDK_USING_ADC2
#define SDK_USING_ADC2_DEVICE ADC2
#define SDK_USING_ADC2_IN0 "PA1"
#define SDK_USING_GPIOA
#define SDK_USING_GPIOA_DEVICE GPIOA
#define SDK_USING_GPIOB
#define SDK_USING_GPIOB_DEVICE GPIOB
#define SDK_USING_GPIOC
#define SDK_USING_GPIOC_DEVICE GPIOC
#define SDK_USING_GPIOD
#define SDK_USING_GPIOD_DEVICE GPIOD
#define SDK_USING_GPIOD_KEY0 "PD0"
#define SDK_USING_GPIOD_KEY1 "PD1"
#define SDK_USING_GPIOD_KEY2 "PD3"
#define SDK_USING_GPIOD_KEY3 "PD4"
#define SDK_USING_GPIOD_LED5 "PD8"
#define SDK_USING_GPIOD_LED6 "PD10"
#define SDK_USING_GPIOE
#define SDK_USING_GPIOE_DEVICE GPIOE
#define SDK_USING_GPIOF
#define SDK_USING_GPIOF_DEVICE GPIOF
#define SDK_USING_GPIOG
#define SDK_USING_GPIOG_DEVICE GPIOG
#define SDK_USING_USR1
#define SDK_USING_USR1_DEVICE USR1
#define SDK_USING_USR2
#define SDK_USING_USR2_DEVICE USR2
#define SDK_USING_USR3
#define SDK_USING_USR3_DEVICE USR3
#define SDK_USING_SFUD
#define SDK_USING_SHELL
#define SDK_USING_USR
#define SDK_USING_USRQ
#define SDK_USING_TESTCASE_UART
#define SDK_USING_TESTCASE_LED
#define SDK_USING_TESTCASE_GUI
#define SDK_USING_TESTCASE_SHELL
#define SDK_USING_TESTCASE_N6

#endif /* SDKCONFIG_H */