#ifndef HCONFIG_H
#define HCONFIG_H

#define HCONFIG_BOARD "LADRC_BOARD"
#define HCONFIG_CHIP "CH32V307VCT6"
#define HCONFIG_CHIP_SERIES "CH32"
#define HCONFIG_CHIP_SUBSERIES "CH32V307"
#define HCONFIG_CHIP_VENDOR "WCH"
#define HCONFIG_LAST_MODIFIED "2025-11-24 23:41:28"

#define SDK_USING_USART0
#define SDK_USING_USART2
#define SDK_USING_USART3
#define SDK_USING_SPI1
#define SDK_USING_SPI2
#define SDK_USING_SPI3
#define SDK_USING_I2C1
#define SDK_USING_I2C2
#define SDK_USING_I2C3
#define SDK_USING_ADC1
#define SDK_USING_ADC2
#define SDK_USING_GPIOA
#define SDK_USING_GPIOB
#define SDK_USING_GPIOC
#define SDK_USING_GPIOD
#define SDK_USING_GPIOE
#define SDK_USING_GPIOF
#define SDK_USING_GPIOG
#define SDK_USING_USR1
#define SDK_USING_USR2
#define SDK_USING_USR3
#define SDK_USING_SFUD
#define SDK_USING_SHELL
#define SDK_USING_USR
#define SDK_USING_TESTCASE_UART
#define SDK_USING_TESTCASE_LED
#define SDK_USING_TESTCASE_GUI
#define SDK_USING_TESTCASE_SHELL

#endif /* HCONFIG_H */