#ifndef SDKCONFIG_H
#define SDKCONFIG_H

#define SDKCONFIG_BOARD "RISCV"
#define SDKCONFIG_CHIP "CH32V307VCT6"
#define SDKCONFIG_CHIP_SERIES "CH32"
#define SDKCONFIG_CHIP_SUBSERIES "CH32V3"
#define SDKCONFIG_CHIP_VENDOR "WCH"
#define SDKCONFIG_LAST_MODIFIED "2026-03-12 17:49:16"

// 管脚定义说明:
// USART1 - TX: PA9
// USART1 - RX: PA10
// USART1 - BaudRate: 115200
// USART1 - ISR: 0
// USART2 - TX: PD5
// USART2 - RX: PD6
// USART2 - BaudRate: 9600
// USART2 - ISR: 1
// UART4 - TX: PB0
// UART4 - RX: PB1
// UART4 - BaudRate: 9600
// UART4 - ISR: 0
// UART6 - TX: PC0
// UART6 - RX: PC1
// UART6 - BaudRate: 9600
// UART6 - ISR: 0
// UART7 - TX: PE12
// UART7 - RX: PE13
// UART7 - BaudRate: 115200
// UART7 - ISR: 0
// UART8 - TX: PE14
// UART8 - RX: PE15
// UART8 - BaudRate: 115200
// UART8 - ISR: 0
// SPI2 - SCK: PB12
// SPI2 - MISO: PC13
// SPI2 - MOSI: PC14
// SPI2 - CS: PB12
// SPI3 - SCK: PB3
// SPI3 - MISO: PDB4
// SPI3 - MOSI: PB5
// SPI3 - CS: PA15
// I2C2 - SCL: PB8
// I2C2 - SDA: PB9
// I2C3 - SCL: PA8
// I2C3 - SDA: PC9
// GPIOD - KEY0: PD0
// GPIOD - KEY1: PD1
// GPIOD - KEY2: PD3
// GPIOD - KEY3: PD4
// GPIOD - LED5: PD8
// GPIOD - LED6: PD10
// TIM2 - ARR: 9
// TIM2 - PSC: 9599
// TIM6 - ARR: 9
// TIM6 - PSC: 9599
// TIM7 - ARR: 9
// TIM7 - PSC: 9599
// TIM3 - PIN_A: PA6
// TIM3 - PIN_B: PA7
// TIM4 - PIN_A: PB6
// TIM4 - PIN_B: PB7
// TIM5 - PIN_A: PA0
// TIM5 - PIN_B: PA1
// TIM8 - PIN_A: PC6
// TIM8 - PIN_B: PC7
// TIM9 - PWM1: PD9
// TIM9 - PWM2: PD11
// TIM9 - PWM3: PD13
// TIM9 - PWM4: PD15
// M1 - PIN1: PE0
// M1 - PIN2: PE1
// M2 - PIN1: PE2
// M2 - PIN2: PE3
// M3 - PIN1: PE4
// M3 - PIN2: PE5
// M4 - PIN1: PE6
// M4 - PIN2: PE7

#define SDK_USING_USART1
#define SDK_USING_USART1_DEVICE USART1
#define SDK_USING_USART1_TX "PA9"
#define SDK_USING_USART1_RX "PA10"
#define SDK_USING_USART1_BAUDRATE 115200
#define SDK_USING_USART1_ISR 0
#define SDK_USING_USART2
#define SDK_USING_USART2_DEVICE USART2
#define SDK_USING_USART2_TX "PD5"
#define SDK_USING_USART2_RX "PD6"
#define SDK_USING_USART2_BAUDRATE 9600
#define SDK_USING_USART2_ISR 1
#define SDK_USING_UART4
#define SDK_USING_UART4_DEVICE UART4
#define SDK_USING_UART4_TX "PB0"
#define SDK_USING_UART4_RX "PB1"
#define SDK_USING_UART4_BAUDRATE 9600
#define SDK_USING_UART4_ISR 0
#define SDK_USING_UART6
#define SDK_USING_UART6_DEVICE UART6
#define SDK_USING_UART6_TX "PC0"
#define SDK_USING_UART6_RX "PC1"
#define SDK_USING_UART6_BAUDRATE 9600
#define SDK_USING_UART6_ISR 0
#define SDK_USING_UART7
#define SDK_USING_UART7_DEVICE UART7
#define SDK_USING_UART7_TX "PE12"
#define SDK_USING_UART7_RX "PE13"
#define SDK_USING_UART7_BAUDRATE 115200
#define SDK_USING_UART7_ISR 0
#define SDK_USING_UART8
#define SDK_USING_UART8_DEVICE UART8
#define SDK_USING_UART8_TX "PE14"
#define SDK_USING_UART8_RX "PE15"
#define SDK_USING_UART8_BAUDRATE 115200
#define SDK_USING_UART8_ISR 0
#define SDK_USING_SPI2
#define SDK_USING_SPI2_DEVICE SPI2
#define SDK_USING_SPI2_SCK "PB12"
#define SDK_USING_SPI2_MISO "PC13"
#define SDK_USING_SPI2_MOSI "PC14"
#define SDK_USING_SPI2_CS "PB12"
#define SDK_USING_SPI3
#define SDK_USING_SPI3_DEVICE SPI3
#define SDK_USING_SPI3_SCK "PB3"
#define SDK_USING_SPI3_MISO "PDB4"
#define SDK_USING_SPI3_MOSI "PB5"
#define SDK_USING_SPI3_CS "PA15"
#define SDK_USING_I2C2
#define SDK_USING_I2C2_DEVICE I2C2
#define SDK_USING_I2C2_SCL "PB8"
#define SDK_USING_I2C2_SDA "PB9"
#define SDK_USING_I2C3
#define SDK_USING_I2C3_DEVICE I2C3
#define SDK_USING_I2C3_SCL "PA8"
#define SDK_USING_I2C3_SDA "PC9"
#define SDK_USING_GPIOA
#define SDK_USING_GPIOA_DEVICE GPIOA
#define SDK_USING_GPIOB
#define SDK_USING_GPIOB_DEVICE GPIOB
#define SDK_USING_GPIOC
#define SDK_USING_GPIOC_DEVICE GPIOC
#define SDK_USING_GPIOD
#define SDK_USING_GPIOD_DEVICE GPIOD
#define SDK_USING_GPIOD_KEY0 "PD0"
#define SDK_USING_GPIOD_KEY1 "PD1"
#define SDK_USING_GPIOD_KEY2 "PD3"
#define SDK_USING_GPIOD_KEY3 "PD4"
#define SDK_USING_GPIOD_LED5 "PD8"
#define SDK_USING_GPIOD_LED6 "PD10"
#define SDK_USING_GPIOE
#define SDK_USING_GPIOE_DEVICE GPIOE
#define SDK_USING_GPIOF
#define SDK_USING_GPIOF_DEVICE GPIOF
#define SDK_USING_GPIOG
#define SDK_USING_GPIOG_DEVICE GPIOG
#define SDK_USING_TIM2
#define SDK_USING_TIM2_DEVICE TIM2
#define SDK_USING_TIM2_ARR 9
#define SDK_USING_TIM2_PSC 9599
#define SDK_USING_TIM6
#define SDK_USING_TIM6_DEVICE TIM6
#define SDK_USING_TIM6_ARR 9
#define SDK_USING_TIM6_PSC 9599
#define SDK_USING_TIM7
#define SDK_USING_TIM7_DEVICE TIM7
#define SDK_USING_TIM7_ARR 9
#define SDK_USING_TIM7_PSC 9599
#define SDK_USING_TIM3
#define SDK_USING_TIM3_DEVICE TIM3
#define SDK_USING_TIM3_PIN_A "PA6"
#define SDK_USING_TIM3_PIN_B "PA7"
#define SDK_USING_TIM4
#define SDK_USING_TIM4_DEVICE TIM4
#define SDK_USING_TIM4_PIN_A "PB6"
#define SDK_USING_TIM4_PIN_B "PB7"
#define SDK_USING_TIM5
#define SDK_USING_TIM5_DEVICE TIM5
#define SDK_USING_TIM5_PIN_A "PA0"
#define SDK_USING_TIM5_PIN_B "PA1"
#define SDK_USING_TIM8
#define SDK_USING_TIM8_DEVICE TIM8
#define SDK_USING_TIM8_PIN_A "PC6"
#define SDK_USING_TIM8_PIN_B "PC7"
#define SDK_USING_TIM9
#define SDK_USING_TIM9_DEVICE TIM9
#define SDK_USING_TIM9_PWM1 "PD9"
#define SDK_USING_TIM9_PWM2 "PD11"
#define SDK_USING_TIM9_PWM3 "PD13"
#define SDK_USING_TIM9_PWM4 "PD15"
#define SDK_USING_M1
#define SDK_USING_M1_DEVICE M1
#define SDK_USING_M1_PIN1 "PE0"
#define SDK_USING_M1_PIN2 "PE1"
#define SDK_USING_M2
#define SDK_USING_M2_DEVICE M2
#define SDK_USING_M2_PIN1 "PE2"
#define SDK_USING_M2_PIN2 "PE3"
#define SDK_USING_M3
#define SDK_USING_M3_DEVICE M3
#define SDK_USING_M3_PIN1 "PE4"
#define SDK_USING_M3_PIN2 "PE5"
#define SDK_USING_M4
#define SDK_USING_M4_DEVICE M4
#define SDK_USING_M4_PIN1 "PE6"
#define SDK_USING_M4_PIN2 "PE7"
#define SDK_USING_USR1
#define SDK_USING_USR1_DEVICE USR1
#define SDK_USING_USR2
#define SDK_USING_USR2_DEVICE USR2
#define SDK_USING_USR3
#define SDK_USING_USR3_DEVICE USR3
#define SDK_USING_SFUD
#define SDK_USING_SHELL
#define SDK_USING_USR
#define SDK_USING_USRQ
#define SDK_USING_TESTCASE_UART
#define SDK_USING_TESTCASE_LED
#define SDK_USING_TESTCASE_GUI
#define SDK_USING_TESTCASE_SHELL
#define SDK_USING_TESTCASE_N6

#endif /* SDKCONFIG_H */