/*
 * board_config.h
 *
 *  Created on: 2025Äê7ÔÂ20ÈÕ
 *      Author: MCU
 */

#ifndef USER_BOARD_CONFIG_H_
#define USER_BOARD_CONFIG_H_

/* Board Drivers Configuration */
#define LDARC_DEVICE_ADC
#define LDARC_DEVICE_I2C2
#define LDARC_DEVICE_KEY
#define LDARC_DEVICE_LED
#define LDARC_DEVICE_SPI2
#define LDARC_DEVICE_SPI3
#define LDARC_DEVICE_TIM2
#define LDARC_DEVICE_TIM3
#define LDARC_DEVICE_TIM4
#define LDARC_DEVICE_TIM5
#define LDARC_DEVICE_TIM6
#define LDARC_DEVICE_TIM7
#define LDARC_DEVICE_TIM8
#define LDARC_DEVICE_TIM9
#define LDARC_DEVICE_UART2
#define LDARC_DEVICE_UART4
#define LDARC_DEVICE_UART6
#define LDARC_DEVICE_UART7
#define LDARC_DEVICE_UART8

/* Board Component Configuration */
#define LDARC_COMPONENT_CHERRYRB
#define LDARC_COMPONENT_FLASH
#define LDARC_COMPONENT_LETTER_SHELL
//#define LDARC_COMPONENT_LVGL
#define LDARC_COMPONENT_MPU6050
#define LDARC_COMPONENT_MULTITIMER
#define LDARC_COMPONENT_CHERRYRB
#define LDARC_COMPONENT_SFUD
#define LDARC_COMPONENT_TFT
#define LDARC_COMPONENT_TFT_OFF
#define LDARC_COMPONENT_VOFA
#define LDARC_COMPONENT_USR_PRINTF
#define LDARC_COMPONENT_LADRC
#define LDARC_COMPONENT_SIMULATION
//#define LDARC_COMPONENT_OLED

#endif /* USER_BOARD_CONFIG_H_ */
